server:
  port: 1010
spring:
  datasource:
    url: jdbc:mysql://101.34.45.254:3306/nightCityBlog?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: nightcity
mybatis:
  mapper-locations: classpath:mapper/*.xml

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 3600
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 设置cookie的SameSite属性，允许跨域请求
  same-site: None
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-128
  # 是否输出操作日志
  is-log: true
  # 设置cookie的Secure属性，启用https
  secure: true