server:
  port: 1010
spring:
#  redis配置
  redis:
#   redis服务ip 例：host: 192.168.1.1
    host:
#   端口
    port:
#   密码，没有可以空着，但是建议改端口+设密码，我第一次用的时候没有修改用的默认，不出两个小时服务器直接崩
    password:
# mysql设置
  datasource:
    url:
#   url: jdbc:mysql:/mysql服务器ip地址:端口号/数据库名?useUnicode=true&characterEncoding=utf8
#   url: jdbc:mysql:/localhost:8080/user?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
#    用户名
    username:
#   密码
    password:

  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.qq.com
    #发送者邮箱
    username: 2274233006@qq.com
    #配置密码,注意不是密码，而是申请到的smtp授权码
    password: password
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sa-token:
  # token名称 (同时也是cookie名称)，这个名称前端发的时候需要加在请求头里，前端代码axios封装文件中有注释
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 3600
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 设置cookie的SameSite属性，允许跨域请求
  same-site: None
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-128
  # 是否输出操作日志
  is-log: true
  # 设置cookie的Secure属性，启用https
  secure: true