server:
  port: 1010
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 60MB
  redis:
    host: 101.34.45.254
    port: 8888
    password: nightCity
  datasource:
    url: jdbc:mysql://101.34.45.254:6666/nightCityBlogs?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: nightCity

  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.qq.com
    #发送者邮箱
    username: 2274233006@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: ooigaubzpqoieajc
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
ftp-centos:
  #IP
  host: 101.34.45.254
  #端口
  port: 22
  user: root
  password: 151537Zx
  basePath: /nightCityBlogs
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 3600
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 设置cookie的SameSite属性，允许跨域请求
  same-site: None
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-128
  # 是否输出操作日志
  is-log: true
  # 设置cookie的Secure属性，启用https
  secure: true